### ISSUE TITLE
EntityFramework Core - OnDelete behavior for self referencing tables

### ISSUE THREAD

**Issue by ivrljic** [IntentArchitect/Support#102]
### Ask a question

Hello,

We have a situation where one of our tables is having foreign key to itself to create a linked list.
The created configuration for the domain item has its delete behavior set to Cascade but the EF is not agreeing with that.
When we manually set the OnDelete behavior to Restrict the migration works but Intent overrides our changes.
Is it possible to set some kind of Stereotype to define the delete behavior?

Section from domain item Configuration file:
![image](https://github.com/user-attachments/assets/ab81d40b-2414-4a89-b0c8-df4afb5c90c8)

Error in the EF:
Introducing FOREIGN KEY constraint 'FK_Products_Products_SuccessorId' on table 'Products' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
Could not create constraint or index. See previous errors.

Database: SQL Server 
Framework: EF 8
Intent Template: Clean Architecture

**Comment by joelsteventurner** [comment]
Hi @ivrljic 

Just double checking a few things and I'll get back to you shortly

**Comment by joelsteventurner** [comment]
@ivrljic 

I have just run through a few scenarios our side, I see if I have a model like this if setting the OnDelete behaviour to be `DeleteBehavior.Cascade`, which is incorrect. I have logged this as a bug change this behaviour so that this type of Scenario results in a `DeleteBehavior.Restrict`

![image](https://github.com/user-attachments/assets/f7716820-de31-460c-8956-bf238fa6837a)

Can I confirm your model is similar, i.e. you have a composite owner relationship (i.e. Black Diamond) relationship into the Self referencing table?

Just want to make sure the Bug I have found, is the scenario you are experiencing.

As an interim workaround you can plavce an `// IntentIgnore` above that code to change the delete behaviour

```csharp
            // IntentIgnore
            builder.HasMany(x => x.AggSelves)
                .WithOne()
                .HasForeignKey(x => x.ParentId)
                .IsRequired()
                .OnDelete(DeleteBehavior.Restrict);
```

**Comment by ivrljic** [comment]
Hello, 

it is similar. We have an enitity that inherits a base entity that has a reference to itself as seen in the image.

In the Attribute overview on the Product table the Successor looks like this:
![image](https://github.com/user-attachments/assets/427588ac-dd80-44ca-ba03-ebf2b988675d)
![image](https://github.com/user-attachments/assets/4699e1d1-adc1-463b-901d-c28d3c1b6cb3)


![image](https://github.com/user-attachments/assets/508fd105-98b9-4a2a-8608-95bbb2b51291)

**Comment by joelsteventurner** [comment]
@ivrljic 

I can also suggest, you could mapping this relationship as one of the following. Self-referencing tables is often more naturally an aggregational relationship (white diamond) rather than a compositional relationship (black diamond).

![image](https://github.com/user-attachments/assets/8c27bd26-db34-4798-a175-c0613e4cdf0c)

**Comment by ivrljic** [comment]
Yeah, this seems to fix it when both sides are 0..1.
Thank you!
