### ISSUE TITLE
CRUD for Bridging tables

### ISSUE THREAD

**Issue by ZardusMukon** [IntentArchitect/Support#17]
### Ask a question

Good morning, 

I have a quick question regarding domain associations and to what extend IA manages CRUD services for bridging tables. 

We have two independent tables:

- `Person`
- `WorkDescription`

There is a many-to-many association between these two. (A person can have multiple work descriptions, a work description can be assigned to multiple persons). 

The user can link existing persons to existing work descriptions (so this linking is NOT part of the CRUD services of either).

Setting up an m-m association does result in the migration script creating a bridging table (this is what we want)

But I don't see an easy way to create the CRUD services for this bridging table. 

Do we have to create it manually or am I missing something in intent to handle this?

I can kind of see why Intent won't "see" the bridging table, but I just want to make sure.

**Comment by JonathanLydall** [comment]
Hi @ZardusMukon,

You're correct that Intent doesn't know about the joining table because it's a table which EF Core creates and manages completely internally for the many-to-many relationship.

You can however manually create this joining table yourself and you will then be able to see it from the `Services` designer. You would change your domain model from something like:

![image](https://github.com/IntentArchitect/Support/assets/1290262/dd7db1de-71fa-45df-a33c-b76e1e5122ac)

To instead be something like:

![image](https://github.com/IntentArchitect/Support/assets/1290262/f67706a9-97f8-4220-bc7c-852e9ee495a5)

The `PersonWorkDescription` class will then be visible in the `Services` designer when trying to create CRUD services or mappings.
