### ISSUE TITLE
IdentityServer4 and ASP.Net Core Web Application

### ISSUE THREAD

**Issue by mrk007dvt** [IntentArchitect/Support#19]
### What happened?

![image](https://github.com/IntentArchitect/Support/assets/111583018/3c331a96-35c4-480c-9fe7-d45112525f5e)
![image](https://github.com/IntentArchitect/Support/assets/111583018/88713242-e487-46eb-859b-85e57631720a)
There is a warning - "Detected package version outside of dependency constraint: IdentityServer4...

### What version of Intent Architect are you using?

4.0.0

**Comment by JonathanLydall** [comment]
Hi @mrk007dvt,

The issue here is that the `IdentityServer4` NuGet packages pre-emptively restricted themselves to a particular major version of `AutoMapper` and as there are other packages installed which use a newer version of AutoMapper, this is causing the warning. 

Because the `IdentityServer4` authors have moved to their commercial (but otherwise functionally identical) Duende packages, these older `IdentityServer4` packages are no longer receiving updates from them.

We can however confirm from experience that running 12.0.0 of `AutoMapper` with `IdentityServer4` packages does not actually cause any problems in practice, despite the warning.

Short of trying to downgrade `AutoMapper` versions, one would need to upgrade to the newer but non-free `Duende` packages to fully address this warning.
