### ISSUE TITLE
Application template - generate projects based on installation modules

### ISSUE THREAD

**Issue by Laura-BSC** [IntentArchitect/Support#23]
### Ask a question

We have an application template used to create projects using our default project structure and to install the components we typically use, which can be toggled based on specific project requirements. 

Our projects typically use Azure Functions and Service Bus and we have modules to facilitate the creation of these. Our application template creates projects for the various templates to be installed (for example, an Azure Functions Project is created and the templates related to functions are placed there), for example:

![image](https://github.com/IntentArchitect/Support/assets/57346928/792b8a2b-f763-40fe-903d-84dfc44a436d)

The issue is that sometimes our projects don't need all our default modules installed. We can toggle the modules to be installed with no issue (the module is not installed), however, the empty project is still created

![image](https://github.com/IntentArchitect/Support/assets/57346928/e11b18a5-c886-485a-987e-43d0aaf4bff7)

Is there a way to configure the application template so that it only creates the project if a specific module is installed?

Here's a snippet from our application template:

![image](https://github.com/IntentArchitect/Support/assets/57346928/13fbff93-6376-4c98-a816-b788a5bd4be7)

**Comment by Laura-BSC** [comment]
Thanks @dandrejvv, that got me quite far, however, my template is fairly complex in terms of the number of optional modules and thus the number of projects that are generated based on what is selected. Complicating things further is that some modules need to install on the same project but can be installed independently. 

When I install most of the modules, it generates the Visual Studio designer more or less as I would expect it (there are a few templates that are not placed in the correct place based on their role (and default location in some cases). However, there are 3 modules that if I choose to install them, cause the output to give odd results (see the screenshots below for examples):

Installed modules:
![image](https://github.com/IntentArchitect/Support/assets/57346928/8a4dbe79-6dbd-4e7d-ac66-96296526f63f)

Visual Studio designer with a few issues:
![image](https://github.com/IntentArchitect/Support/assets/57346928/fec3e9de-abcf-479c-b70c-00f3ab8649e2)

Installing our AutoMapper module in addition:
![image](https://github.com/IntentArchitect/Support/assets/57346928/0c43f108-3f20-400a-bee9-b0a397b6e574)

**Comment by dandrejvv** [comment]
Hi @Laura-BSC , the main reason those templates are placed there and highlighted as errors is because the Roles specified in those Templates could not be found in the Solution structure. Does your metadata install any new Roles that those templates make use of?

**Comment by dandrejvv** [comment]
Hi @Laura-BSC . I notice a huge difference between the first and second screenshot. Maybe we should talk over our support channel to get to the bottom of this issue.

**Comment by JonathanLydall** [comment]
Hi @Laura-BSC,

Thanks for taking the time earlier for us to go through this together to ensure this was working for you.

Just to re-cap for the benefit of anyone else coming across this thread, the scenario was essentially as follows:

- An application template had:
  - Installation metadata to add a set of projects to the Visual Studio designer.
  - Had an optional component unticked by default which would install `Module A` and `Module B`.
- `Module A` had installation metadata to add a new `Project A` project to the Visual Studio designer and this project would contain `Role A`.
- `Module B` would install `Template Output B` which was targeting `Role A`.

After using the application template and selecting the optional component, then in the Visual Studio designer `Template Output B` was not being assigned to `Project A` even though it had the `Role A` role inside of it.

The fix was to add a `<dependency />` to `Module B`'s `.imod` file for `Module A` and ensure you are running at least Intent Architect 4.0.1 which now ensures modules are installed in order of dependency which would result in `Module A`'s installation metadata being added to the Visual Studio designer so that when `Module B` was installed afterwards it would find `Role A` and put its `Template Output B` into the correct place.
