### ISSUE TITLE
Disable creation of file in specific scenario

### ISSUE THREAD

**Issue by leonAtRain** [IntentArchitect/Support#24]
### Ask a question

I'm adding the Drool engine to my project and in the module that provides the functionality, I need a common class -but that common class needs to rely on a specific Domain, which is ConstraintRef - I don't want to create the domain if it's not there, I would rather not add the common Drool compiler.

I want to do something like this:

  public override ITemplate CreateTemplateInstance(IOutputTarget outputTarget)
      {
          if (_metadataManager.Domain(outputTarget.Application).GetClassModels().Any(c => c.Name.Equals("ConstraintRef")))
          {
              return new DroolRuleCompilerTemplate(outputTarget);
          }
          // don't create the file:
          return IJavaTemplate;
      }

**Comment by dandrejvv** [comment]
Hi @leonAtRain.
To control whether a Template generates code or not can be achieved in one of two ways:

## Make use of a custom Registration that controls whether Templates even get created or not.

In your Module Builder Designer, select the Template in question and change the Type to `Custom`.

![image](https://github.com/IntentArchitect/Support/assets/7236289/2e8953fb-f35d-4963-a2ca-86769fe92d85)

The Template's Registration class will now have a different method `DoRegistration` (instead of `CreateTemplateInstance`) which allows you to control whether Templates get created and registered at all depending on a certain criteria (i.e. "is there a class with the name `ConstraintRef` ?")

```c#
[IntentManaged(Mode.Fully, Body = Mode.Ignore)]
public void DoRegistration(ITemplateInstanceRegistry registry, IApplication applicationManager)
{
    if (_metadataManager.Domain(applicationManager).GetClassModels().Any(c => c.Name.Equals("ConstraintRef")))
    {
        registry.RegisterTemplate(TemplateId, project => new DroolRuleCompilerTemplate(project, null));
    }
}
``` 

Thus, if a Template is not registered, it won't be created and so there won't be an output file generated by the Software Factory.

## Have the Template override the CanRunTemplate() method so that even on registration, it doesn't generate any code.

Alternatively, in your Template Partial class, override the `CanRunTemplate()` method like so (assuming you have your Template Type set to `Single File` in your case):

```c#
public override bool CanRunTemplate()
{
    return Model.Any(c => c.Name.Equals("ConstraintRef"));
}
```

This will determine whether this Template instance can generate code or not based on the CanRunTemplate result.

**Comment by leonAtRain** [comment]
I have decided to use the override method, which seemed a lot simpler, but because I have the Single file option, I implemented it like this:
        public override bool CanRunTemplate()
        {
            return ExecutionContext.MetadataManager.Domain(ExecutionContext.GetApplicationConfig().Id).GetClassModels().Any(c => c.Name.Equals("ConstraintRef"));
        }
Then I see this in the SF :

![image](https://github.com/IntentArchitect/Support/assets/129200997/ca972c9d-7149-4ecf-b159-2c0d49f7d616)
