### ISSUE TITLE
Application Template - 'Include By Default' toggle for module doesn't work as expected

### ISSUE THREAD

**Issue by Laura-BSC** [IntentArchitect/Support#31]
### What happened?

I wanted to update my application template so that certain modules are no longer included by default. Changing the toggle does not prevent the module from being included by default.

![image](https://github.com/IntentArchitect/Support/assets/57346928/469e0944-d201-440c-a4b7-2ab5a3302cb9)
![image](https://github.com/IntentArchitect/Support/assets/57346928/c9d7fe7a-418f-4f93-8c00-cd91b00fd84e)

On further inspection of 'metadata.iatspec', I discovered that the component element has an attribute 'included' which isn't updated when the toggle is changed, but rather, there is a nested element 'includedByDefault' that is changed. If I manually change  'included="true"' to '"included="false"', the module is not selected by default when I create a new project using the application template.

![image](https://github.com/IntentArchitect/Support/assets/57346928/c66abc82-25c1-4efd-8e88-1cb3b1df1783)

### What version of Intent Architect are you using?

4.0.1-pre.13

### Additional information

Please note that this issue was occurring on version 4.0.0 of Intent Architect as well

**Comment by JonathanLydall** [comment]
Hi @Laura-BSC,

Because you've applied the option on the `Module`, it affects whether or not it is uncheckable on the list of modules when expanding components on the right of the Application Template UI.

To control whether a _Component_ `Is required` you will need to use the option on the `Component` element (`Azure Functions` in your screenshot).

**Comment by Laura-BSC** [comment]
Thanks, completely missed that
