### ISSUE TITLE
"Finalizing Execution" step never completes

### ISSUE THREAD

**Issue by jpseini** [IntentArchitect/Support#36]
### What happened?

I am busy updating all of our modules to use the latest version of the Intent Modules, and be 100% v4 compatible.

In v4 of IA, I opened up our various modules, and updated all modules to the latest version, then ran the SF.  The factory seems to execute correctly, and does update the files on disk, however the final step does not complete (I waited 5+ minutes)

![image](https://github.com/IntentArchitect/Support/assets/45011398/33840d1e-af0f-470a-ba59-298311c51938)

Running the `dotnet build` command in the CLI results in the project being built without any issue within a second or two.

### What version of Intent Architect are you using?

4.0.1

**Comment by jpseini** [comment]
Just to add to this - I have tested with 4 different modules, all with the same issue.

**Comment by JonathanLydall** [comment]
Hi @jpseini,

This module has been changed somewhat recently to be more reliable on Linux and macOS and this issue is something that has cropped up which we had worked on to solve. Essentially the issue is that `dotnet build` by default uses stay resident "build servers" to make builds performed in quick succession faster, so it seems like the process never ends.

We have put code that should prevent using of build servers, but it's apparently not working for you.

Can you please confirm the following:

- `Intent.ModuleBuilder.AutoCompile` module is at the latest, it should be `3.3.5`.
- The result of running `dotnet --version` from a terminal (mine is `7.0.304` in case you're curious).

**Comment by jpseini** [comment]
Hi @JonathanLydall 

I can confirm 3.3.5 of AutoCompile:
![image](https://github.com/IntentArchitect/Support/assets/45011398/25d3c3cc-c875-41b3-a048-432ccf27f724)

.NET version is 7.0.302:
![image](https://github.com/IntentArchitect/Support/assets/45011398/f98262e9-43ed-4994-b7c3-fd334d8a3b82)

(I can try updating to 304, if you think that might make a different and test?)

**Comment by JonathanLydall** [comment]
Thanks @jpseini, although not a bad idea, I am doubtful that such a minor update to dotnet would make a difference here.

Can you try running the following from your terminal and see if afterwards the SF for the module stops getting stuck?

```
dotnet build-server shutdown
```

**Comment by jpseini** [comment]
Hi @JonathanLydall  - unfortunately the command had no effect, I am still experiencing the issue.

Oddly enough - as I'm working my way through updating our modules, I just came across a module which _does_ execute. There is no obvious difference (modules referenced, or Nuget versions) I can between this one and the other 9 which don't execute.

**Comment by JonathanLydall** [comment]
Hi @jpseini,

The `Intent.ModuleBuilder.AutoCompile` module version `3.3.6` has been updated to be more robust in this regard and should no longer have this issue.
