### ISSUE TITLE
Incorrect application name used in template

### ISSUE THREAD

**Issue by jpseini** [IntentArchitect/Support#5]
### Ask a question

I am encountering an odd scenario, where for a specific user, running the software factory will output change files, but for values from another application.

In this example, the ApplicationName is used to populate the underlined field, but the software factory wants to change the field from "ApplicationX" (the actual application name) to "ApplicationY" (the name of another application)

I suspect its some caching issue, as the above scenario is not experienced on all user's PCs.

My actual question: Is there a cache folder which is "safe" to delete which should hopefully resolve this? Thanks

**Comment by dandrejvv** [comment]
Hi @jpseini , thank you for your question. If the problem relates to a caching issue, there is a Modules folder cache that you can delete and have Intent fetch the latest modules from the configured module repositories. You can find this cached folder...
MyIntentApp\intent\.intent\modules.
If this doesn't resolve your problem, we can investigate further.

**Comment by JonathanLydall** [comment]
Hi @jpseini,

Definitely odd that it seems to be picking up a different application's name. 

Although I suspect you're already aware, you can delete the cache of downloaded modules from the `modules` folder under the `.intent` folder which can be found easily by looking at a solution's settings:
 
![image](https://user-images.githubusercontent.com/1290262/233074197-85c7b9e9-5e05-4b31-89f8-e7ccf3037849.png)

The only other sort of cache file is the `.output.log` file which is stored alongside the `.application.config` file, as per this path in an application's settings:

![image](https://user-images.githubusercontent.com/1290262/233074465-b9ef5356-b3c3-4196-9fbb-68baacfc5955.png)

This file stores information from the previous software factory execution, like where a particular template for a particular model was output to. The SF uses it to work out if a file is being renamed or needs to be deleted. The `OnceOff` generation option also uses this file to determine if a file was generated in the past and should therefore not be generated again. One can delete this file as the SF will re-create it on the next run, but just be aware that once off files will try generate again and any renames/deletions since the previous SF run won't be detected.
