### ISSUE TITLE
Template only output if Visual Studio designer is opened

### ISSUE THREAD

**Issue by jpseini** [IntentArchitect/Support#64]
### Ask a question

Sounds odd, but I have a situation where it seems like some (but not all) templates do not get output when the SF is run, unless the Visual Studio designer has been opened.

In my use case, a new application is created using our own template. Executing the SF runs without error - except some templates are just not output. Opening up the Visual Studio designer, and then running the SF (and being prompted to save changes in the Visual Studio Designer even though no changes were explicitly made) and the files are output.

I cannot see anything obviously different with the template files in question vs those which always output. 

Is this something you have seen and know what might be cause it? I can consistently reproduce it if a demo will help?

**Comment by JonathanLydall** [comment]
Hi @jpseini,

The only theory I can think of without having a problematic application to look at, is that those templates aren't generated because they need a stereotype to be present and auto-applying stereotypes aren't added in the VS designer until its opened and saved.

This theory can be tested by comparing the designer files before and after saving in the VS designer.

Regardless, if you want to privately send me a zip of the just created application with it in the problematic state I can investigate further, ensure the following:

- The application has had the initial SF changes applied.
- Has not had the VS designer opened and saved.
- The zip has `.intent` folder included as it has the "restored" custom modules in it so that I will be able to run everything.

**Comment by jpseini** [comment]
Thanks @JonathanLydall 

The issue is definitely related to the stereotype not being added then. The output of the files are controlled by a checkbox loaded via a stereotype.

Is there anything we can do to mitigate this? Or currently, the user must just make sure to open up the Visual Studio designer before running the SF?

**Comment by JonathanLydall** [comment]
It depends on what stereotypes are missing, but perhaps it would it have your application installation metadata source have the stereotypes already applied?

**Comment by jpseini** [comment]
Thanks @JonathanLydall - unfortunately in our use case that won't work as the stereotype is added by an optionally installed module. Can't force it as part of the application metadata.

But I will give this some thought and see if I can make it work - Thank you for the feedback though, I will go ahead and close the ticket.
