### ISSUE TITLE
How to generate class diagram from db first approach ?

### ISSUE THREAD

**Issue by priyav232** [IntentArchitect/Support#83]
### Ask a question

how to generate class diagram in intent architect tool to generate domain and corresponding CRUD from database model (database first approach) ?

**Comment by dandrejvv** [comment]
Good day @priyav232 .
Thank you for your question.
Are you asking how to import an existing database schema into Intent Architect's domain designer in order to generate code from that model?

If that is the case, we do have a tool that you can use to import from an existing SQL Server database.
You can find it here: https://github.com/IntentArchitect/Intent.SqlSchemaExtractor

Please let me know if you have any further questions.
